apiVersion: apps/v1
kind: Deployment
metadata:
  name: tardigrade-gateway
  labels:
    app: tardigrade-gateway
spec:
  selector:
    matchLabels:
      app: tardigrade-gateway
  template:
    metadata:
      labels:
        app: tardigrade-gateway
    spec:
      containers:
        - name: tardigrade-gateway
          image: storjlabs/gateway
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 7777
          volumeMounts:
            - name: tardigrade-config
              mountPath: "/etc/tardigrade/"
            - name: minio-config
              mountPath: "/etc/tardigrade/minio/"
          args:
            - run
            - --config-dir=/etc/tardigrade
      volumes:
        - name: tardigrade-config
          secret:
            secretName: tardigade-config
            items:
              - key: config.yaml
                path: config.yaml
        - name: minio-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tardigrade-gateway-internal
spec:
  selector:
    app: tardigrade-gateway
  ports:
    - port: 7777
      targetPort: 7777
